version: '3.0'

services:
  server:
    build: ./server
    container_name: server
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - nodenet

  db:
    image: mysql:8.3
    command:
      - --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/createTable.sql:/docker-entrypoint-initdb.d/createTable.sql
      - ./db/my.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet
    ports:
      - "3306:3306"

  app:
    build: ./app
    container_name: app
    restart: on-failure
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node src/main.cjs
    ports:
      - "80:3000"
    depends_on:
      - db
    networks:
      - nodenet
    volumes:
      - ./app/src:/var/www/html/src

networks:
  nodenet:
    driver: bridge
